name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.9' # Specify the Julia version you need

      # Step 3: Set up cache for dependencies
      - name: Setup cache
        uses: julia-actions/cache@v2

      # Step 4: Install dependencies (registered and unregistered)
      - name: Install Dependencies
        run: |
          julia -e '
            import Pkg;
            # Add unregistered dependency from GitHub
            Pkg.develop(PackageSpec(url="https://github.com/JuliaSNN/SpikingNeuralNetworks.jl"));
            # Install all dependencies listed in Project.toml
            Pkg.instantiate();
          '

      # Step 5: Run tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      # Step 6: Upload test results on failure
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test/
